version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - db
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    restart: on-failure

  db:
    image: mysql:latest
    volumes:
      - ./setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
      - ./conf/infile:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    cap_add:
      - SYS_NICE
    restart: on-failure

  app:
    image: matomo:latest
    depends_on:
      - db
    environment:
      - MATOMO_DATABASE_HOST=db
    restart: on-failure
