version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - db
      - app
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/<your-domain>/:/etc/ssl/private
    ports:
      - 80:80
      - 443:443
    restart: on-failure

  db:
    image: mysql:latest
    volumes:
      - ./setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    cap_add:
      - SYS_NICE
    restart: on-failure

  app:
    image: matomo:latest
    depends_on:
      - db
    environment:
      - MATOMO_DATABASE_HOST=db
    restart: on-failure
