version: "3"

services:
  nginx:
    image: nginx:latest
    depends_on:
      - db
      - app
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl/certbot/conf:/etc/letsencrypt:z
      - ./ssl/certbot/www:/var/www/certbot:z
    ports:
      - 80:80
      - 443:443
    restart: on-failure
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    

  certbot:
    image: certbot/certbot
    volumes:
      - ./ssl/certbot/conf:/etc/letsencrypt:z
      - ./ssl/certbot/www:/var/www/certbot:z
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    

  db:
    image: mysql:latest
    volumes:
      - ./setup-db.sql:/docker-entrypoint-initdb.d/setup-db.sql
    environment:
      - MYSQL_ROOT_PASSWORD=your_password
    cap_add:
      - SYS_NICE
    restart: on-failure

  app:
    image: matomo:latest
    depends_on:
      - db
    environment:
      - MATOMO_DATABASE_HOST=db
    restart: on-failure
